### PR TITLE
Setting view causes state change on default view

### PR DESCRIPTION
**Pull request by trevorrjohn**
This PR fails at this moment I was hoping someone could help me debug why it fails.

### CODE REVIEW

**Comment by trevorrjohn** [comment]
So I found the issue, `#merge_fields` was using `#merge!` which is modifies the object.

**Comment by nolanprocore** [comment]
Hi Trevor. Thanks so much for contributing. We'll take a look soon.

**Comment by philipqnguyen** [comment]
lgtm

**Comment by philipqnguyen** [comment]
whoops didnt mean to accidentally close this

**Comment by trevorrjohn** [comment]
No rush, but as this is a bug fix I would love to get this merged and released so that I don't have to maintain a fork.

**Pull request merged**
