### PR TITLE
add mongoid support.

### PR DESCRIPTION
**Pull request by ayamomiji**
or maybe just use `object.respond_to?(:to_a)`?

### CODE REVIEW

**Comment by ayamomiji** [comment]
https://www.rubydoc.info/github/mongoid/mongoid/Mongoid%2FDocument:to_a
since all mongoid documents are respond to `to_a`, the solution seems not quite appropriate :(

**Comment by philipqnguyen** [comment]
thanks for the PR @ayamomiji 

`to_a` won't work out of the box because Hash objects also responds to `to_a`.

On top of that, we can't claim to support Mongoid if we don't add tests and appropriate README.

However, before you start doing anymore work on this PR (because I don't want you to waste your time), I have some concerns that should be addressed first. Namely, should Blueprinter support Mongoid? If we do, we need to maintain tests, docs, and ensure future features to be compatible for Mongoid as well. I'm actually leaning towards not supporting mongoid, but can be persuaded.

cc. @mcclayton @AllPurposeName @dlcarter @adamwells @jl4ever @nolanprocore @njbbaer @wai-procore

**Comment by mcclayton** [comment]
I agree with @philipqnguyen in that, if we were to support Mongoid directly from within Blueprinter, we'd want to fully support it via documentation, testing, adding it to our compatibility checks/roadmap, etc.

**Comment by mcclayton** [comment]
Thank you so much again for your contribution @ayamomiji,

**Comment by mcclayton** [comment]
Thank you so much again for your contribution @ayamomiji,
Apologies, but as mentioned above, this is not something we plan to directly support as implemented here, however, I created an issue here https://github.com/procore/blueprinter/issues/153 to track/ideate/create a more extensible approach to providing configurable ORM/ODM support. In the meantime, please feel free to fork Blueprinter and use your implementation if you need this support immediately. Going to go ahead and close this PR for now.

**Pull request closed without merging**
