### PR TITLE
chore: setup github stuff

### PR DESCRIPTION
**Pull request by jmeridth**
- [x] switch to 2.7+ ruby versions in tests
- [x] github actions for tests and release instead of circleci
- [x] dependabot
- [ ] ~stale github action~ postponing until we've reviewed all existing issues and PRs
- [x] auto assign author github action
- [x] update README tests badge
- [x] add CONTRIBUTING.md, CODE_OF_CONDUCT.md, and .github/PULL_REQUEST_TEMPLATE.md
- [x] put secrets into github

### CODE REVIEW

**Comment by jmeridth** [comment]
Note: All versions of Ruby are [EOL](https://endoflife.date/ruby), we should look at changing CI to accept 2.7+ only.

**Review by lessthanjacob — APPROVED** [review]

**Comment by jmeridth** [comment]
Looks like the current github action failures (ruby 2.2) are related to [this](https://github.com/ruby/setup-ruby/issues/496).  No fix available. Going to go back to newer versions of ruby.

**Comment by jmeridth** [comment]
This is working with 2.7 but fails with ruby 3.0+.  Will fix for 3.0+ and handle 2.7 retroactively due to known legacy apps that are using blueprinter.

**Comment by jmeridth** [comment]
@lessthanjacob fixing the build failures.  Awesome.  Thank you.

Now getting the secrets in place so once this merges to `master` it publishes to rubygems.

**Review by jamesmcguirepro — APPROVED** [review]

**Review by lessthanjacob — APPROVED** [review]

**Comment by jmeridth** [comment]
@lessthanjacob @jamesmcguirepro I simplified the release github action.  One more review and this is ready to merge IMO.

**Pull request merged**
