### PR TITLE
Allow blueprint to define a mapping for the rendered object

### PR DESCRIPTION
**Pull request by Systho**
PR related to  #92

### CODE REVIEW

**Comment by philipqnguyen** [comment]
The specs are failing because circle ci runs the specs at ruby 2.2.2 which is the minimum supported ruby version for blueprinter. You might want to add `require 'delegate'` since it doesn't seem like it is automatically loaded in 2.2.x

**Comment by vinaya-procore** [comment]
This is a nice idea!

But I think it will create more confusion, as `Blueprinter` will end up having `field`, `fields`, and `mapping` to choose from. I see the convenience that `mapping` block brings, enabling multiple methods to be grouped together. But I do not really feel that it provides better value than what `field` already offers, grouping things that do not necessarily belong together.

I recommend that we stick to using `field` as a block when serializing an association that's not directly related to the object.

Thanks.

**Comment by Systho** [comment]
@vinaya-procore  actually the point is not to group multiple methods together but to be able to have an association return a collection which is not immediately on the object.

The initial idea was to allow `association` to receive block (like `field` do ) but when I wrote that implementation I realised that it brought some duplication which was hiding the concept of an mapper object.

I can rewrite the DSL to simply allow passing block to association but I would really suggest that technically those blocks are just adding methods to an invisible wrapper around the rendered object.

**Comment by philipqnguyen** [comment]
@Systho we can accept a PR that adds block to `association` if you're still up for it, but `mapping` is too much of a change to the public interface.

**Comment by philipqnguyen** [comment]
@Systho you're right that there isn't a clear path to storing blocks. Currently `Field` stores an instance of the BlockExtractor and the block itself, which may or may not be the best way. One of the focus I'm hoping to tackle in the foreseeable future is to cut down on time spent inside blueprinter when serializing ruby objects. SimpleDelegator uses `method_missing` to match the method calls, which can be slow. 

I ran a quick ruby-prof test on your branch:

```ruby
# Using a blueprint like this
class ProfilerBlueprint < Blueprinter::Base
  identifier :id
  fields :attr_1,
         :attr_2,
         :attr_4,
         :attr_5,
         :attr_6,
         :attr_7,
         :attr_8,
         :attr_9,
         :attr_10,
         :attr_11,
         :attr_12,
         :attr_13,
         :attr_14,
         :attr_15,
         :attr_16,
         :attr_17,
         :attr_18,
         :attr_19,
         :attr_20,
         :attr_21
  view :normal do
    fields :attr_22, :attr_25
    field :attr_23, name: :renamed_attr
  end
  view :extended do
    include_view :normal
    field :attr_24
  end
  view :special do
    include_view :extended
    exclude :attr_25
  end
end

objects = 100.times.map {obj}
require 'ruby-prof'
RubyProf.measure_mode = RubyProf::PROCESS_TIME
RubyProf.start
ProfilerBlueprint.render(objects, view: :special)
result = RubyProf.stop
printer = RubyProf::FlatPrinter.new(result)
printer.print(STDOUT)
```

this branch process time: 0.359882
master branch process time: 0.225519

Obviously those results comes from my machine so the exact number will be different, but I think the difference is pretty significant. If the decision is between speed or using a delegator, I will have to pick speed, considering that speed is an important aspect of a serializer.

**Comment by philipqnguyen** [comment]
Closing this PR which also closes #92

reopen the issue if you wish for further discussion.

**Pull request closed without merging**
