### PR TITLE
fix field exclusion for views

### LINKED ISSUE #207: exclude :field does not work as expected for views
Hello! I found small bug with field exclusion and views:

```ruby
class Print < Blueprinter::Base
  field :first_name
  field :last_name

  view :exclude_last_name do
    exclude :last_name
  end

  view :foo do
    include_view :exclude_last_name
  end
end

result = Print.render_as_hash({first_name: 1, last_name: 2}, view: :foo)
``` 

Expected:
```ruby
{:first_name=>1}
```

Got:
```ruby
{:first_name=>1, :last_name=>2}
```

### PR DESCRIPTION
**Pull request by tpltn**
Fixes #207

### CODE REVIEW

**Comment by nolanprocore** [comment]
Thanks for contributing. We'll take a look soon.

**Comment by tpltn** [comment]
Hey @nolanprocore, any updates on this?

**Comment by nolanprocore** [comment]
> Hey @nolanprocore, any updates on this?

Not yet. It looks like you've got a spec failure here. Have you taken a look at that yet?

**Comment by tpltn** [comment]
@nolanprocore it seems that rspec-rails 4.0.0 is not compatible with ruby 2.2 - https://github.com/rspec/rspec-rails/blob/master/Changelog.md

rspec-rails 4.0.0 was installed because of 
```
    ammeter (1.1.4)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-rails (>= 2.2)
```

Should I fix build in this PR, or it'll be better to create new one?

**Comment by philipqnguyen** [comment]
@tpltn good find! Would you put up another PR for `gem rspec-rails, '< 4.0.0'` with a comment mentioning that 4.0.0 does not support ruby 2.2? We can quickly merge that and then rebase this PR.

**Comment by tpltn** [comment]
@philipqnguyen no problems - https://github.com/procore/blueprinter/pull/210

**Comment by tpltn** [comment]
@philipqnguyen I rebased this PR onto latest master, tests are green now)

**Comment by tpltn** [comment]
Hi, @philipqnguyen! Can you merge this PR, please?

**Comment by philipqnguyen** [comment]
released in 0.23.3

**Pull request merged**
