### PR TITLE
exclude multiple fields inline

### PR DESCRIPTION
**Pull request by pabhinaya**
@mcclayton , For derived views with multiple included views, ability to exclude multiple fields inline.

### CODE REVIEW

**Comment by mcclayton** [comment]
Yes, if you wouldn't mind adding a test to `view_spec.rb` similar to: https://github.com/procore/blueprinter/blob/master/spec/units/view_spec.rb#L15-L23
and then I can handle drafting up the release/version bump/CHANGELOG entry.

**Comment by pabhinaya** [comment]
@philipqnguyen, @mcclayton  I have added the specs for exclude_fields. Please proceed.

**Comment by ritikesh** [comment]
I believe exclude should be able to take 1 or more arguments. Both the below examples should be valid usages of exclude:

```ruby
exclude :field1
```

```ruby
exclude :field1, :field2
```

This should be possible with Ruby's splat operator.

**Comment by philipqnguyen** [comment]
@ritikesh normally I would agree with your suggestion too, but I think having plural `excludes` would fit with current patterns: ie.,`field` for single and `fields` for multiple fields.

**Pull request merged**
